//
// Created by dieter on 26/02/18.
//

#include <zconf.h>
#include <iostream>
#include "../include/Game.h"
#include "../include/Types.h"
#include "../include/Map.h"
#include "../include/SDLMap.h"

void Game::start(Factory* f) {
    int map[31][14] = {
            {WALL_DOWN_RIGHT,WALL_VERTICAL,WALL_VERTICAL,WALL_VERTICAL,WALL_VERTICAL,WALL_VERTICAL,WALL_VERTICAL,WALL_VERTICAL,WALL_VERTICAL,WALL_VERTICAL,WALL_VERTICAL,WALL_VERTICAL,WALL_VERTICAL,WALL_TOP_RIGHT},
            {WALL_HORIZONTAL,POINT_SMALL,POINT_BIG,POINT_SMALL,POINT_SMALL,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,WALL_HORIZONTAL},
            {WALL_HORIZONTAL,POINT_SMALL,FULL_DOWN_RIGHT,FULL_RIGHT,FULL_TOP_RIGHT,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,WALL_HORIZONTAL},
            {WALL_HORIZONTAL,POINT_SMALL,FULL_DOWN,FULL_CENTERED,FULL_TOP,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,WALL_HORIZONTAL},
            {WALL_HORIZONTAL,POINT_SMALL,FULL_DOWN_LEFT,FULL_LEFT,FULL_TOP_LEFT,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,WALL_HORIZONTAL},
            {WALL_HORIZONTAL,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,WALL_HORIZONTAL},
            {WALL_HORIZONTAL,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,WALL_HORIZONTAL},
            {WALL_HORIZONTAL,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,WALL_HORIZONTAL},
            {WALL_HORIZONTAL,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,WALL_HORIZONTAL},
            {WALL_HORIZONTAL,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,WALL_HORIZONTAL},
            {WALL_HORIZONTAL,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,WALL_HORIZONTAL},
            {WALL_HORIZONTAL,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,WALL_HORIZONTAL},
            {WALL_HORIZONTAL,BLANK,BLANK,BLANK,WALL_T_DOWN,WALL_VERTICAL,WALL_VERTICAL,WALL_VERTICAL,WALL_VERTICAL,WALL_VERTICAL,WALL_VERTICAL,WALL_VERTICAL,WALL_VERTICAL,WALL_T_TOP},
            {WALL_HORIZONTAL,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,WALL_HORIZONTAL},
            {WALL_HORIZONTAL,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,WALL_HORIZONTAL},
            {WALL_HORIZONTAL,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,WALL_HORIZONTAL},
            {WALL_HORIZONTAL,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,WALL_HORIZONTAL},
            {WALL_HORIZONTAL,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,WALL_HORIZONTAL},
            {WALL_HORIZONTAL,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,WALL_HORIZONTAL},
            {WALL_HORIZONTAL,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,WALL_HORIZONTAL},
            {WALL_HORIZONTAL,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,WALL_HORIZONTAL},
            {WALL_HORIZONTAL,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,WALL_HORIZONTAL},
            {WALL_HORIZONTAL,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,WALL_HORIZONTAL},
            {WALL_HORIZONTAL,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,WALL_HORIZONTAL},
            {WALL_HORIZONTAL,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,WALL_HORIZONTAL},
            {WALL_HORIZONTAL,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,WALL_HORIZONTAL},
            {WALL_HORIZONTAL,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,WALL_HORIZONTAL},
            {WALL_HORIZONTAL,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,WALL_HORIZONTAL},
            {WALL_HORIZONTAL,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,WALL_HORIZONTAL},
            {WALL_HORIZONTAL,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,BLANK,WALL_HORIZONTAL},
            {WALL_LEFT_DOWN,WALL_VERTICAL,WALL_VERTICAL,WALL_VERTICAL,WALL_VERTICAL,WALL_VERTICAL,WALL_VERTICAL,WALL_VERTICAL,WALL_VERTICAL,WALL_VERTICAL,WALL_VERTICAL,WALL_VERTICAL,WALL_VERTICAL,WALL_LEFT_TOP}


    };
    int *b[31];
    for(int i = 0;i<31;i++){
        b[i] = map[i];
    }

    //TODO read map from file

    //Init game
    bool quit = false;
    f->initDisplay();
    f->loadMedia();

    Map* tiles = f->createMap(31,14);
    tiles->loadMap(b,BLUE_TILE);
    Event* events = f->createEventSystem();
    PacMan* player = f->createPacMan(250,26,3);
    Ghost* enemy1 = f->createGhost(25,250,3,RED_GHOST);
    Ghost* enemy2 = f->createGhost(180,250,2,BLUE_GHOST);
    Ghost* enemy3 = f->createGhost(170,140,1,PINK_GHOST);

    int playerDirection = DIR_LEFT;
    //Game loop
    while(!quit){
        f->clear();
        switch (events->getEvent()){
            case KEY_PRESS_QUIT:
                quit = true;
                break;
            case KEY_PRESS_SURFACE_RIGHT:
                playerDirection = DIR_RIGHT;
                break;
            case KEY_PRESS_SURFACE_LEFT:
                playerDirection = DIR_LEFT;
                break;
            case KEY_PRESS_SURFACE_UP:
                playerDirection = DIR_UP;
                break;
            case KEY_PRESS_SURFACE_DOWN:
                playerDirection = DIR_DOWN;
                break;
            default:
                break;
        }

        player->move(playerDirection);

        if(player->collision(enemy1)){
            std::cout << "Player colliding with ghost1!" << std::endl;
        }

        if(tiles->checkCollision(player)){
            //std::cout << "Player colliding with a Tile!" << std::endl;
            player->pushBack();
        }

        if(tiles->checkCollision(enemy1)){
            enemy1->pushBack();
        }

        tiles->visualize();

        enemy1-> move(playerDirection);
        enemy1->visualize();
        enemy2-> move(DIR_LEFT);
        enemy2->visualize();
        enemy3-> move(DIR_RIGHT);
        enemy3->visualize();
        player->visualize();
        f->render();
    }

    //Close game
    f->close();
}

